### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
This adds the F-Droid link to F-Droid for XprivacyLua

### CODE REVIEW

**Comment by beerisgood** [comment]
Isn't XprivacyLua dead?

**Comment by Poussinou** [comment]
@beerisgood The last commit to [their repo](https://github.com/M66B/XPrivacyLua) is 7 days old, and we added the last version last month on F-Droid as you can see [here](https://f-droid.org/packages/eu.faircode.xlua/). So I don't think it's dead ;)

**Comment by jawz101** [comment]
Regular XPrivacy worked on Android Lollipop and lower.  Marcel made XPrivacyLUA a couple of years ago for Android Marshmallow and higher.

**Comment by beerisgood** [comment]
Okay then I haven't say anything :D

Anyway I prefer blocking stuff (for example with Bloaka) instead of use some funky hooks for manipulating apps which also need Xposed to work

**Comment by jawz101** [comment]
Me too, tbh.  I mean, I do like the idea of being able to carve out the exact bit of info and give them crap too :P

**Pull request merged**
